### ISSUE TITLE
CLA assistant v2

### ISSUE THREAD

**Issue by thojansen** [cla-assistant/cla-assistant#118]
This issue tracks the progress for *v2*. **Any feedback is highly appreciated** as quite a lot of changes are planned for this major release. One of the fundamental changes is that we want to switch to signing on a per-repo basis to signing on a per-CLA basis. Thus, in the future, contributors would only sign a CLA once in order to contribute to all projects having that CLA assigned. Please let us know what you think about that. Also let us know in case you want to help us out.

- [x] Ping Event for Webhooks - #109
- [x] Sign CLA instead of signing CLA per repo #66 
- [x] Store more information about signer #64 
- [x] Linking of multiple repos (possibly organisations) at once #62 
- [x] Nicer Error Pages #48 
- [x] List of my signed CLAs #35
- [ ] angular2/ es6 #117
- [ ] Add Contributors to GitHub team #108  
- [ ] Import List of E-Mails #98

**Comment by thojansen** [comment]
@brbmi @jenlampton @jdanyow @EisenbergEffect @ejsmith @niemyjski @sdirix @reem @dcrosta @matz3 @yaseminc @dfarr @benboeser @dtornow @pmn @bkeepers @brntbeer

**Comment by bkeepers** [comment]
> One of the fundamental changes is that we want to switch to signing on a per-repo basis to signing on a per-CLA basis. Thus, in the future, contributors would only sign a CLA once in order to contribute to all projects having that CLA assigned.

This is really interesting. The only question I have is if there is enough legal clarity around the scope of what I am agreeing to when I accept the CLA. How do I know which repositories it applies to? When new repositories start using that CLA in the future, how do I know that I'm contributing to a project covered by a CLA I previously accepted?

/cc @mlinksva

**Comment by thojansen** [comment]
Yes, I agree. Currently we see that this is usually defined in the CLA text itself, stating that you are contributing to SAP/ some other company or some open source foundation regardless on how this is integrated into the PR flow of a single repository.

Similar to the oauth flow we could also show the "scope" of the CLA and ask again in case of new and not yet agreed repositories. Do you think that would be a valid use case from a contributors perspective? Accepting a CLA for one repo and not for another one seems also strange, as you would likely not create a PR in the first place. However giving explicit consent on the covered scope of a CLA sounds reasonable.

Anyway we wanted to start this discussion here before making any decisions. We are also checking internally with our legal team, but also need all other views on this.

**Comment by mlinksva** [comment]
In "on a per-CLA basis" is a CLA unique to an organization? I imagine it must be. If so "per-organization" would be clearer than "per-CLA". Whether on a repo or organization basis, a new CLA is going to require new consent.

Per repo and org seem like use cases one or the other of which a recipient or contributor (or contributor's employer) might prefer.

**Comment by niemyjski** [comment]
No it's on a per repo which sucks :(

**Comment by camlorn** [comment]
I'm looking at adopting CLA Assistant.  My feedback thus far:

We need per repository agreements.  I see the appeal of per organization agreements, but I'm an individual with no legal department.  CLA Assistant's support for per-repository signing is a major draw for me due to the extra clarity of scope.  If I could have my way, I'd actually go further: I consider per pull request to be ideal.  The signing process is not onerous and clicking two links per repository (or per pull request) is not really a problem.  If a project wants to be convenient to contributors over all else, they can just not have a CLA and deal with the restrictions that imposes.  things like making CI pass and obeying code style guides are way more trouble than signing a CLA through this project.

Secondly, I'm blind.  It would be nice if a bit of attention was paid to accessibility.  Currently, the admin interface can be used because I'm an advanced enough user to know how to deal with the unlabeled buttons and the weird selection list things.  But it's time consuming and inconvenient.  I think moving to Angular 2 fixes a lot of this, and I'm willing to provide further feedback.  I'd implement it for you, but I can't check the visual impact of my changes and that makes web frontend very hard.  Fortunately, the actual signing process is accessible enough.

**Comment by thojansen** [comment]
@camlorn if you could help out on the accessability part that would be awesome. Reporting open issues or half finished PRs on that end would help a lot (whatever works best). So far angular 2 is still challenging for productive usage but we plan to give it another try soon. Now we have one more reason to switch.

Regarding CLA signing, we now plan to support it either per repo (as it is now), or per organization (based on the feedback in this thread). That is then up for the owner/ admin to decide what works best. And we plan to release that part independently.

**Comment by thojansen** [comment]
We have now shipped v1.4 ahead of v2.0 with the option to sign a CLA per org instead of doing it per repo. Some parts like the porting to angular2 are moved to v2.0 as there were some technical challenges (also angular2 is still not released as of writing this). Thanks for your valuable input on this. Since this was mainly about discussing how to proceed with the signing process, we are closing this issue and track individual ones going forward. :shipit: 🎉
